# Generated by Django 3.0.7 on 2020-11-22 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import hierarchy.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPTTGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propagate', models.BooleanField(default=True)),
                ('inheritable', models.BooleanField(default=True, help_text='Set group permissions as inheritable for others nodes. Provide a value to HIERARCHY_MPTT_METHOD to establish inheritance criteria.')),
                ('max_children', models.PositiveIntegerField(blank=True, help_text='Maximum number of children for this node', null=True)),
                ('active', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('group', models.OneToOneField(blank=True, help_text='The group this node relates to. A user will get all permissions granted to each of their groups.', on_delete=models.SET(hierarchy.models.get_sentinel_tree), related_name='hierarchy_set', related_query_name='hierarchy', to='auth.Group', verbose_name='group')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hierarchy.MPTTGroup', verbose_name='parent')),
            ],
            options={
                'ordering': ('tree_id', 'lft'),
                'unique_together': {('parent', 'group')},
            },
            managers=[
                ('tree', django.db.models.manager.Manager()),
            ],
        ),
    ]
